### PR TITLE
disable transitive deps, improve README

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

I made the README easier to read by adding syntax highlighting. I also changed the mode of some files from 755 to 644 as it's quite unusual.

The last thing is that some implicit deps were missing, I added them and set `implicit_transitive_deps` to false so it won't happen again.

Cheers,

### CODE REVIEW

**Comment by gborough** [comment]
@zapashcanon  Thanks really appreciated, approved

**Comment by gborough** [comment]
@zapashcanon btw I am new to ocaml and this is my first publish, seems like the documentation is missing on https://ocaml.org/p/safemoney/latest, do you know what to do to fix it? I thought it was supposed to be automatic once the odoc style doc are included. Thanks

**Comment by zapashcanon** [comment]
Well, the documentation building system that has been added to ocaml.org is [quite complicated](https://icfp21.sigplan.org/details/ocaml-2021-papers/15/A-Multiverse-of-Glorious-Documentation) (compared to [alternatives](https://icfp21.sigplan.org/details/ocaml-2021-papers/4/Digodoc-and-Docs)).

My advice would be to wait a few days to see if it suddenly appears. At some point, if it's still not there you could ask on [discuss](https://discuss.ocaml.org/t/how-to-make-the-documentation-of-a-package-available-on-ocaml-org/13011).

**Comment by gborough** [comment]
@zapashcanon thanks I will keep an eye out for this

**Pull request merged**
